### PR TITLE
Deprecate manual salt option for password_hash

### PR DESCRIPTION
**Pull request by adduc**

### CODE REVIEW

**Comment by adduc** [comment]
I'm not comfortable with the error suppression in the modified unit tests, but it was recommended in PHPUnit's documentation and I didn't know any other method to ignore the deprecated warning.

**Comment by odolbeau** [comment]
Why do you want to deprecate the salt options?
It doesn't seems to be deprecated: http://php.net/manual/en/function.password-hash.php

**Comment by ircmaxell** [comment]
The salt option is deprecated in PHP7 and moving forward. See this thread: http://marc.info/?t=142782791400003&r=1&w=2

**Comment by GrahamCampbell** [comment]
> It doesn't seems to be deprecated: http://php.net/manual/en/function.password-hash.php

Those docs aren't updated for php 7 yet.

**Comment by ircmaxell** [comment]
@GrahamCampbell want to take a stab at updating them?

**Comment by GrahamCampbell** [comment]
I've not been following the changes, so wouldn't do a complete job.

**Comment by odolbeau** [comment]
Thanks for the link @ircmaxell! :)
As we need to provide a custom salt for a specific need (I'll be glad to discuss this if you want) I would like to know if you planned to merge this PR soon?

**Comment by ircmaxell** [comment]
@odolbeau can you explain this specific need?

**Pull request closed without merging**
